### PR TITLE
Replace class with interface

### PR DESCRIPTION
**Pull request by feloy**

### CODE REVIEW

**Comment by ladyleet** [comment]
@kwonoj ruh oh. Halp?

**Comment by ladyleet** [comment]
@kwonoj what failed?

**Comment by feloy** [comment]
I think is that TravisCI is "connected" to the repo but not yet configured. And it fails by default :(
I will try and create a first configuratuon by tomorrow

**Comment by kwonoj** [comment]
@ladyleet Yes, I enabled it but haven't created configs for if anyone interested in contribution. https://github.com/ReactiveX/rxjs-docs/issues/18 . I can do if anyone's not interested in.

**Comment by ladyleet** [comment]
@kwonoj can we merge this now?

**Comment by kwonoj** [comment]
@ladyleet :ship: I'll enable protected branch shortly too.

**Pull request merged**
