### PR TITLE
SharedModule, ToolbarModule

### PR DESCRIPTION
**Pull request by Only1MrAnderson**
refactor(Component): Created Shared Module and moved the toolbar to its own component

### CODE REVIEW

**Comment by Only1MrAnderson** [comment]
I am lost on this danger file failure. Is this on my end or a problem with Travis-ci?

**Comment by ladyleet** [comment]
highway to the danger zone! pinging @kwonoj for comments on this. thx @Only1MrAnderson !

**Comment by kwonoj** [comment]
Please rebase to master includes danger update.

**Comment by Only1MrAnderson** [comment]
@kwonoj  Updated

**Comment by ladyleet** [comment]
@kwonoj or @btroncone can one of you review and merge this?

**Comment by btroncone** [comment]
@Only1MrAnderson This is currently out of date, could you update? Everything else lgtm, thanks! 👍

**Comment by Only1MrAnderson** [comment]
@kwonoj  Danger file issue again? Otherwise updated @btroncone 
```
The command "if [ -n "DANGER_GITHUB_API_TOKEN" ]; then echo {} > ./.babelrc && npx danger; fi" exited with 1.
```

**Comment by kwonoj** [comment]
@Only1MrAnderson no, it's valid. should conform danger comments: https://github.com/ReactiveX/rxjs-docs/pull/58#issuecomment-338355952

**Comment by ladyleet** [comment]
@Only1MrAnderson sure, whatever you like.

**Comment by Only1MrAnderson** [comment]
@ladyleet  Please close in favor of #135 . I think I finally have done the process. 👍

**Pull request closed without merging**
