### PR TITLE
refactor(Components): change to app.module and lazy loaded modules

### PR DESCRIPTION
**Pull request by Only1MrAnderson**
refactor(Components): change to app.module and lazy loaded modules to use the shared module. change to app.component to use new toolbar component

### CODE REVIEW

**Comment by ladyleet** [comment]
@Only1MrAnderson whoops, can you update the branch? @btroncone good to merge if you're 👍  too.

**Comment by Only1MrAnderson** [comment]
Please hold off on the merge, found a layout issue with the refactor.

**Comment by Only1MrAnderson** [comment]
@sumitarora @ladyleet  G2G

**Comment by ashwin-sureshkumar** [comment]
@sumitarora or @ladyleet - can I get approvals before the merge since there is code change after your initial approval. Thanks !

**Comment by ladyleet** [comment]
@ashwin-sureshkumar LGTM

**Pull request merged**
