### PR TITLE
docs(main page and installation): add content to home page

### PR DESCRIPTION
**Pull request by yashints**
added content to main page: installation guide #17

### CODE REVIEW

**Comment by JWO719** [comment]
Cool thanks for your contribution! Will checkout and give some feedback!

**Comment by JWO719** [comment]
travis failed due to an invalid commit message. I think the scope doesn't allow whitespaces. Could you fix it? If you need help, just ping me

**Comment by ladyleet** [comment]
@JWO719 thank you so much for reviewing! :)

**Comment by yashints** [comment]
Created a new one

**Pull request closed without merging**
