### PR TITLE
fix(Header menu button): added value on the menu hamburger button

### PR DESCRIPTION
**Pull request by knittingcodemonkey**
Tiny pull request to fix a little accessibility issue.

gitignore updated

### CODE REVIEW

**Comment by sumitarora** [comment]
@knittingcodemonkey Can you update the commit message?

**Comment by knittingcodemonkey** [comment]
I've changed the commit message multiple times trying to pass this commit message test. What am I missing?

**Comment by JWO719** [comment]
Can I provide some help with this, or isn't this needed anymore?

**Comment by knittingcodemonkey** [comment]
This has been merged as part of a new commit. All is well. thank you!

**Pull request closed without merging**
