### PR TITLE
updated all components to lazy loaded

### PR DESCRIPTION
**Pull request by Only1MrAnderson**
Updated route module and creating feature modules and routes. Also had to update the material files and tags to get the application to run based on version bump. #27

### CODE REVIEW

**Comment by Only1MrAnderson** [comment]
Apologies for all the noise on this pull request. Still getting used to git, I spend all my days in TFS

**Comment by ladyleet** [comment]
@kwonoj can you review this? this okay? maybe another set of angular eyes would help... @btroncone?

**Comment by kwonoj** [comment]
LGTM, once I got second eye from @btroncone will check this in.

**Comment by btroncone** [comment]
Looks good, could you set a preloading strategy to `PreloadAllModules`? Thanks! @Only1MrAnderson

**Pull request merged**
