### PR TITLE
chore(tooling): Add prettier, lint-staged and precommit hook for tooling

### LINKED ISSUE #45: Basic tooling
anyone up for setting up lint / prettier, etcs for consistent codes? except prettier it's available in RxJS repo already so copy-paste would be sufficient.

### PR DESCRIPTION
**Pull request by ashwin-sureshkumar**
- Added basic tooling configuration for linting using prettier, tslint.
- Added precommit to run lint on staged files

Close #45

### CODE REVIEW

**Comment by ashwin-sureshkumar** [comment]
cc @kwonoj

**Comment by ladyleet** [comment]
LGTM. @kwonoj ? (Thx @ashwin-sureshkumar )

**Comment by athomann** [comment]
Would it sense to run the tests in the pre-commit hook?

**Comment by ashwin-sureshkumar** [comment]
@athomann - There is a discussion about the same in the issue #45

**Comment by kwonoj** [comment]
> Would it sense to run the tests in the pre-commit hook?

No. Commit occurs quite frequent and commit chunk can create test failures will make daily flow painful.

**Comment by ladyleet** [comment]
@ashwin-sureshkumar can you update the branch pls?

**Comment by ashwin-sureshkumar** [comment]
@ladyleet - Done !

**Comment by ladyleet** [comment]
@ashwin-sureshkumar 👍

**Pull request merged**
