### PR TITLE
feat(Tooling): Add prettier, lint-staged and precommit hook for tooling

### LINKED ISSUE #45: Basic tooling
anyone up for setting up lint / prettier, etcs for consistent codes? except prettier it's available in RxJS repo already so copy-paste would be sufficient.

### PR DESCRIPTION
**Pull request by ashwin-sureshkumar**
- Added basic tooling configuration for linting using prettier, tslint.
- Added precommit to run lint on staged files

Close #45

### CODE REVIEW

**Comment by kwonoj** [comment]
I think this scope need to be chore(package) instead of feat. Feature usually specifies actual code changes.

**Comment by ashwin-sureshkumar** [comment]
@kwonoj - Closing this PR and will open another with updated commit message.

**Comment by kwonoj** [comment]
Uh why not amend commit message?

**Comment by ashwin-sureshkumar** [comment]
Sorry, I already closed and sent another one.

**Pull request closed without merging**
