### PR TITLE
refactor(operators): presentation components

### PR DESCRIPTION
**Pull request by jotatoledo**
* Set changeDetection to OnPush for dumb components
* Add explicit return types to getters in `OperatorComponent`
* Add explicit return type to `SafeUrlPipe`

### CODE REVIEW

**Comment by sumitarora** [comment]
@jotatoledo Please resolve conflicts.

**Comment by ladyleet** [comment]
@jotatoledo hi! have you had time to resolve these conflicts?

**Comment by jotatoledo** [comment]
Hey sorry for the delay, totally forgot to update the PR. 
Looks like a WIP commit got mixed on my local, I think Ill have to revert the commit.

**Comment by ashwin-sureshkumar** [comment]
@jotatoledo - Thanks for the PR, nice work.

**Comment by ladyleet** [comment]
Thx @ashwin-sureshkumar! Also thx @jotatoledo for contributing!

**Pull request merged**
