### PR TITLE
chore(packages) Upgrade to Angular v5

### PR DESCRIPTION
**Pull request by feloy**
Refs Issue #150

### CODE REVIEW

**Comment by ashwin-sureshkumar** [comment]
@feloy - Can we locked down exact version numbers of all the packages.

**Comment by ashwin-sureshkumar** [comment]
@feloy Thank you!

**Comment by ashwin-sureshkumar** [comment]
@btroncone @sumitarora - One more approval and I can merge this in.

**Comment by btroncone** [comment]
Do we want to make this 5.0.2 instead?

**Comment by ladyleet** [comment]
Thanks @feloy!

**Comment by ladyleet** [comment]
Oops sorry fat fingers on my phone :)

**Pull request merged**
