### PR TITLE
fix (accessibility): change open external pages in new tab

### LINKED ISSUE #258: UX Improvement: make external pages open in a new tab
All external links should be opened in a new tab to prevent leaving the current website.

### PR DESCRIPTION
**Pull request by saiprasad2595**
Close #258

### CODE REVIEW

**Comment by saiprasad2595** [comment]
Thanks @ashwin-sureshkumar for review.Can you tell me where i am doing wrong in case of commit message as it is my first PR. I am using 
"fix (fix): open external pages in new tab"

**Comment by ashwin-sureshkumar** [comment]
@saiprasad2595 - I fixed your commit and squashed your commits into one commit. (note: there were couple of weird merge commits)

Few things to be noted, 

1. Commit message should be `<type>(<scope>): <subject>` - so no space between type and scope bracket. 

2. Please add `Close #<issue-no>` in the description. This will auto close the issue once the PR is merged in. This helps the change log as well and efficiency in not closing issues manually.  

3. Your initial commit message did not meet guidelines, so that needed as well. 

Again, nice work ! Let the PRs flow. 

cc @ladyleet

**Comment by ashwin-sureshkumar** [comment]
@JWO719 - Could I get a second approval on this please ?

**Comment by saiprasad2595** [comment]
Thanx a ton @ashwin-sureshkumar  . Will sure keep those points in my next commits.

**Pull request merged**
